### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by TheRanker** [AlphaMode/TheOneProbe-Fabric#2]
having a crash with the one probe fabric 1.18 5.1.0
minecraft 1.18.2
fabric 0.13.3
i have a modpack im developing and i just switched to this mod in the 1.18.2 version
ended up getting crash
https://pastebin.ubuntu.com/p/YmFQ9X7Dyj/

tested with vanilla fabric and the one probe and works as intended. so its a mod interaction at the cause of it.

**Comment by TheRanker** [comment]
[crash-2022-03-30_18.15.17-client.txt](https://github.com/AlphaMode/TheOneProbe-Fabric/files/8383954/crash-2022-03-30_18.15.17-client.txt)
[crash-2022-03-30_18.12.52-client.txt](https://github.com/AlphaMode/TheOneProbe-Fabric/files/8383955/crash-2022-03-30_18.12.52-client.txt)
[crash-2022-03-30_18.08.42-server.txt](https://github.com/AlphaMode/TheOneProbe-Fabric/files/8383956/crash-2022-03-30_18.08.42-server.txt)


any fix?

**Comment by AlphaMode** [comment]
I'll look into this today sorry for the late response

**Comment by AlphaMode** [comment]
My best guess is another mod is shipping a different version of forge config

**Comment by TheRanker** [comment]
Forge config? Ummm.  Interesting. I'll get back to you on that

**Comment by AlphaMode** [comment]
A full log would also be helpful

**Comment by TheRanker** [comment]
[crash-2022-04-20_16.53.00-client.txt](https://github.com/AlphaMode/TheOneProbe-Fabric/files/8524724/crash-2022-04-20_16.53.00-client.txt)
[latest.log](https://github.com/AlphaMode/TheOneProbe-Fabric/files/8524725/latest.log)

**Comment by AlphaMode** [comment]
I can't seem to actually reproduce this can you try to narrow down what mod is causing this?

**Comment by TheRanker** [comment]
Ur mod is causing this. It's the only mod that errors out and crashes my modpack.  I'll use waila or megene .no issue . Please fix ur mod even crashed me in vanilla when I looked at grass ffs

**Comment by Dragon-Seeker** [comment]
Ngl you should maybe try attempting to see if it is another mod that is causing the issue as a pack of 500+ mods can be quite unstable at times. 

Do such by removing half the mods(Not TheOneProbe) and seeing if it is having the same issue. Rinse and repeat until it stops crashing and then work with the half you just removed. Then one by one see what mod is causing the issue and report back.
