### ISSUE TITLE
[1.18.2] Crash on looking at player head (com.google.gson.JsonParseException)

### ISSUE THREAD

**Issue by erunseelie** [AlphaMode/TheOneProbe-Fabric#5]
Hey, got a crash on looking at a player head (my own) that I placed down.

`[Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "theoneprobe:packet_return_info"
com.google.gson.JsonParseException: Don't know how to turn {} into a Component`

https://mclo.gs/rZDRBJg

**Comment by AlphaMode** [comment]
I think this is a possible mod conflict could you provide a mod list?

**Comment by erunseelie** [comment]
Sure, the head was generated by this mod: https://www.curseforge.com/minecraft/mc-mods/just-player-heads-fabric

**Comment by Austin001316** [comment]
Extra note, happens on 1.19.2 as well

**Comment by SplendidAlakey** [comment]
Seems to not be compatible with any "modded" heads, the easiest example is [Head Index](https://www.curseforge.com/minecraft/mc-mods/headindex). But any structure mods that utilize heads will also crash.

**Comment by SplendidAlakey** [comment]
Fixed in 6.2.2, thank you!
